feat(provider): updates provider to support turning on full gpkg file
ngageoint/opensphere-plugin-geopackage pull request #12
Opened 2021-05-11 23:46 UTC by jsalankey

Uses a new checkbox directive to support turning the full file on, showing a warning in cases with a lot of layers.

2021-05-12 16:04 UTC, schmidtk requested changes

2021-05-12 16:13 UTC, jsalankey commented on src/plugin/geopackage/geopackageprovider.js
> +goog.require('os.ui.data.LayerCheckboxUI');
Woops, yep I meant to do that, just forgot.

2021-05-13 10:30 UTC, schmidtk approved these changes
Approved, will rebuild after we merge ngageoint/opensphere/pull/1269.

2021-05-14 17:01 UTC, merged

2021-05-14 17:04 UTC, schmidtk commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/opensphere-plugin-geopackage/v/1.4.0)
- [GitHub release](https://github.com/ngageoint/opensphere-plugin-geopackage/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: